module.exports = {
  content: [
    "./app/views/**/*.php",
    "./app/views/**/*.html",
    "./app/views/components/**/*.php",
    "./app/views/pages/**/*.php",
    "./public/**/*.php",
    // More specific pattern for JS files    avoid matching node_modules
    "./public/js/**/*.js"
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#003963',
        'primary-light': '#e6f0f7',
        'primary-lighter': '#3a7ca5',
        'primary-dark': '#002e4d',
        'success': '#10b981',
        'success-lighter': '#34d399',
        'success-light': '#d1fae5',
        'success-dark': '#059669',
        'danger': '#ef4444',
        'danger-lighter': '#f87171',
        'danger-light': '#fee2e2',
        'danger-dark': '#dc2626',
        'warning': '#f59e0b',
        'warning-lighter': '#fbbf24',
        'warning-light': '#fef3c7',
        'warning-dark': '#d97706',
        'info': '#0ea5e9',
        'info-lighter': '#38bdf8',
        'info-light': '#e0f2fe',
        'info-dark': '#0284c7',
        'gray-50': '#f9fafb',
        'gray-100': '#f3f4f6',
        'gray-200': '#e5e7eb',
        'gray-300': '#d1d5db',
        'gray-400': '#9ca3af',
        'gray-500': '#6b7280',
        'gray-600': '#4b5563',
        'gray-700': '#374151',
        'gray-800': '#1f2937',
        'gray-900': '#111827',
        'dark': '#000',
        'white': '#fff',
      },
      fontFamily: {
        'heading': ['Merriweather', 'serif'],
        'body': ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Open Sans', 'Helvetica Neue', 'sans-serif'],
      },
      fontSize: {
        'xs': '0.7rem',
        'sm': '0.9rem',
        'md': '1rem',
        'lg': '1.2rem',
        'xl': '1.5rem',
        'xxl': '3.3rem',
      },
      spacing: {
        'xs': '0.5rem',
        'sm': '0.8rem',
        'md': '1rem',
        'lg': '1.5rem',
        'xl': '2rem',
        'xxl': '3rem',
        'xxxl': '5rem',
      },
      borderRadius: {
        'pill': '9999px',
        'md': '0.5rem',
      },
      transitionDuration: {
        'fast': '200ms',
        'normal': '300ms',
      },
      transitionTimingFunction: {
        'ease': 'ease',
      },
    },
  },
  plugins: [],
};